# Usa la imagen oficial de Nginx
FROM nginx:alpine

# Copia la configuración personalizada de Nginx
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Elimina el archivo por defecto
RUN rm /etc/nginx/conf.d/default.conf