# Usa una imagen base con PHP-FPM
FROM php:7.4-fpm-alpine

# Instala algunas extensiones de PHP comunes (opcional)
RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www/html

# Copia los archivos de la aplicación
COPY . .