version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: bridge
